---
- name: Install haproxy
  become: true
  ansible.builtin.apt:
    name: haproxy
- name: Copy haproxy config
  become: true
  ansible.builtin.copy:
    src: haproxy.cfg
    dest: /etc/haproxy/haproxy.cfg
    validate: /usr/sbin/haproxy -f %s -c
  register: haproxy
- name: Reload haproxy
  become: true
  when: haproxy.changed
  ansible.builtin.systemd_service:
    name: haproxy
    state: reloaded
